<?php
$duration = $hotel->get('db_data')->duration;
?>

<div class="module-item-block hotel-block block">
    <div class="menu">
        <a href=".hotel-block" class="item anchor active">
            <?php echo $this->tr('Описание') ?>
        </a>
        <a href=".hotel-form" class="item anchor">
            <?php echo $this->tr('Цены') ?>
        </a>
        <a href=".hotel-plan" class="item anchor">
            <?php echo $this->tr('Маршрут') ?>
        </a>
        <a href=".comments" class="item anchor">
            <?php echo $this->tr('Вопросы') ?>
        </a>
    </div>

    <h1><?= $this->tr($header) ?></h1>

    <?php
    $html =
        '<div class="gallery">'.
            '<ul class="list">';

    $html .=
        '<li data-thumb="' . $hotel->getPlugin('image')->getImage('hr') . '">'.
            '<img src="' . $hotel->getPlugin('image')->getImage('g') . '" alt="">'.
        '</li>';

    foreach ($hotel->getPlugin('images') as $image) {
        $html .=
            '<li data-thumb="' . $image->getImage('hr') . '">'.
                '<img src="' . $image->getImage('g') . '" alt=""></li>'.
            '</li>';
    }

    $html .=
            '</ul>'.
        '</div>';
    echo $html;
    ?>

    <div class="std-text"><?php echo $this->tr($hotel->get('text')) ?></div>

    <div class="attrs-list">
        <div class="row">
            <div class="label"><?php echo $this->tr('Длительность экскурсии') ?>: <?php echo $this->declension($duration, ['час', 'часа', 'часов']) ?></div>

        </div>
        <div class="row">
            <div class="label"><?php echo $this->tr('В стоимость включено') ?></div>
            <div class="row"><?php echo $this->tr('Аренда') ?>
                <a class="popup" href="/transport/mercedes-benz-e-class/"><?php echo $this->tr('Мерседеса Е 211') ?></a>/
                <a href=""><?php echo $this->tr('Мерседеса Виано') ?></a>/
                <a href=""><?php echo $this->tr('Мерседеса Спринтера') ?></a>
            </div>
            <div class="row"><?php echo $this->tr('Входные билеты в Екатерининский дворец и Екатерининский парк') ?></div>
            <div class="row"><?php echo $this->tr('Услуги персонального гида') ?></div>
        </div>
    </div>
</div>

<div class="hotel-form">
    <?php
    $html =
        '<form action="/hotels/get-price/" method="post" class=" common-form">'.
            '<input type="hidden" name="id" value="' . $hotel->getId() . '">'.
            $this->commonForm($commonForm, [
                ['field' => 'date', 'icon' => 'far fa-calendar-alt'],
                ['field' => 'time', 'icon' => 'far fa-clock'],
                ['field' => 'adults', 'icon' => 'fas fa-user'],
                ['field' => 'children', 'icon' => 'fas fa-child'],
            ]).
            '<div class="price-box std-errors"></div>'.
            '<div class="btns">'.
                '<span class="btn yellow order">' . $this->tr('Забронировать') . '</span>'.
            '</div>'.
        '</form>';

    echo $html;
    ?>
</div>

<div class="block white">
    <div class="hotel-plan">
        <h2><?php echo $this->tr('Маршрут экскурсии') ?></h2>
        <?php
        $plan = $hotel->getPlugin('plan');

        $html = '';

        $icons = [
            'museum' => '<i class="fas fa-university"></i>',
            'park'   => '<i class="fas fa-tree"></i>',
            'marker' => '<i class="fas fa-map-marker-alt"></i>',
        ];

        foreach ($plan as $day) {
            $html .=
                '<div class="day">'.
                    '<div class="stage">'.
                        '<div class="icon">' . $icons[$day->get('icon')] . '</div>'.
                    '</div>'.
                    '<div class="desc">'.
                        '<div class="header">'. $this->tr($day->get('header')) . '</div>'.
                        '<div class="text">'. $this->tr($day->get('text')) . '</div>'.
                    '</div>'.
                '</div>';
        }

        echo $html;
        ?>
    </div>

    <div class="hotel-comments">
        <?php echo $this->comments([
            'depend_id' => $hotel->getId(),
            'depend_type' => \Comments\Model\Comment::TYPE_EXCURSION,
        ]); ?>
    </div>
</div>


<script>
    $document.ready(function() {
        var $gallery = $('.gallery .list', '.hotel-block');

        $gallery.lightSlider({
            gallery: true,
            galleryMargin: 1,
            item: 1,
            loop: true,
            thumbItem: 5,
            slideMargin: 0,
            enableDrag: false,
            currentPagerPosition: 'left'
        });

        var menu = $('.menu', '.hotel-block');

        var itemsArr = [];
        $('.item', menu).each(function() {
            itemsArr.push({
                top: $($(this).attr('href')).offset().top - 130,
                obj: $(this)
            });
        });

        $document.on('scroll', function() {
            var scrollTop = $(window).scrollTop();
            var flag = true;

            $.each(itemsArr, function (key, item) {
                if(!flag || scrollTop < item.top) {
                    return;
                } else {
                    item.obj.addClass('active').siblings().removeClass('active');
                    //flag = false;
                }
            });

            if(scrollTop > 20) {
                menu.addClass('shadow');
            } else {
                menu.removeClass('shadow');
            }
        });
    });
</script>