<div class="main-block-1 block">
    <div class="box">
        <h1><?php echo $this->tr('Индивидуальные Экскурсии<br>по Санкт-Петербургу') ?></h1>

        <ul class="menu">
            <li><a class="btn c2" href="/excursions/"><?php echo $this->tr('Экскурсии') ?></a></li>
            <li><a class="btn c2" href="/tours/"><?php echo $this->tr('Туры') ?></a></li>
            <li><a class="btn c2" href="/transport/"><?php echo $this->tr('Транспорт') ?></a></li>
        </ul>

        <a class="about" href="/about/"><?php echo $this->tr('О компании Gute Reise') ?></a>
    </div>
</div>

<script>
    $(document).ready(function() {
        var block1 = $('.main-block-1');

        $(window).on('resize', function() {
            var height = $document.height() - $('#header').height() - $('#footer').height();
            var padding = (height - $('.box', block1).height()) / 2;
            block1.css({
                height: height,
                paddingTop: padding
            });
        } ());
    });
</script>