<h1>
    <i class="fa module-icon-<?php echo $this->engine->module->get('module') ?>"></i>
    <?php echo $this->header ?>
</h1>

<div class="panel">
    <a href="<?php echo $model->getPublicUrl() ?>" target="_blank">Показать на сайте</a> |
    <a href="/admin/comments/comments/list/?depend_type=1&depend_id=<?php echo $model->getId() ?>">Комментарии</a>
</div>

<?php $form = $this->editForm ?>
<?php echo $this->form()->openTag($form) ?>
<div class="edit-form std-form">
    <div class="tabs tabs-class" data-name="edit-tabs">
        <div class="tabs-header">
            <div class="tab" data-tab="general">Основное</div>
            <div class="tab" data-tab="plan">План</div>
            <div class="tab" data-tab="links">Связи</div>
            <div class="tab" data-tab="photo">Фото</div>
            <div class="tab" data-tab="seo">SEO</div>
            <div class="tab" data-tab="text">Текст</div>
        </div>
        <div class="tabs-body">
            <div class="tab" data-tab="general">
                <?php
                echo $this->adminFormRow($form->get('background-image'));
                echo $this->adminFormRow($form->get('image-image'));
                echo $this->adminFormRow($form->get('nationality'));
                echo $this->adminFormRow($form->get('name'));
                echo $this->adminFormRow($form->get('header'));
                echo $this->adminFormRow($form->get('header_desc'));
                echo $this->adminFormRow($form->get('preview'));
                echo $this->adminFormRow($form->get('options[date]'));
                echo $this->adminFormRow($form->get('db_excursion_id'));
                echo $this->adminFormRow($form->get('url'));
                echo $this->adminFormRow($form->get('place_and_time'));
                echo $this->adminFormRow($form->get('type'));
                ?>
            </div>
            <div class="tab" data-tab="plan">
                <?php
                echo $this->adminFormRow($form->get('place_and_time'));
                echo $this->formRow($form->get('pricetable-collection'));
                echo $this->formRow($form->get('plan-collection'));
                ?>
            </div>
            <div class="tab" data-tab="photo">
                <?php echo $this->formRow($form->get('images-images')); ?>
            </div>
            <div class="tab" data-tab="seo">
                <?php
                echo $this->adminFormRow($form->get('title'));
                echo $this->adminFormRow($form->get('description'));
                ?>
            </div>
            <div class="tab" data-tab="links">
                <?php echo $this->adminFormRow($form->get('tags-collection')); ?>
                <div class="separator">Похожие экскурсии</div>
                <?php echo $this->adminFormRow($form->get('reco-collection')); ?>
                <div class="separator">Связанные достопримечательности</div>
                <?php echo $this->adminFormRow($form->get('museums-collection'));
                ?>
            </div>
            <div class="tab" data-tab="text">
                <?php
                echo $this->adminFormRow($form->get('text'));
                ?>
            </div>
        </div>
    </div>

    <div class="btn-box">
        <span class="btn btn-gray" onclick="history.back()">
            <i class="fa fa-reply"></i>
            Вернутся
        </span>
        <?php if($this->model->getId()) { ?>
            <a class="btn btn-red btn-remove-ck" href="#popup-delete">
                <i class="fa fa-times"></i>
                Удалить
            </a>
        <?php } ?>
        <a class="btn btn-blue btn-submit" href="">
            <i class="fa fa-check"></i>
            Сохранить
        </a>
    </div>
</div>
<?php echo $this->form()->closeTag() ?>

<div id="popup-delete" style="display: none;">
    <div style="text-align: center; margin-bottom: 10px;">Удалить запись?</div>
    <a href="" class="btn btn-green btn-remove" data-id="<?php echo $this->model->getId() ?>"><i class="fa fa-check"></i> Удалить</a>
    <a href="" class="btn btn-red" onclick="$.fancybox.close();"><i class="fa fa-times"></i> Отмена</a>
</div>