<div class="items-list">
    <div class="info-block block">
        <div class="icon"></div>
        <div class="text">
            Транспорт класса люкс с водителем. Идеальное техническое состояние, чистота и комфорт в салоне, водители
            хорошо знают транспортную структуру города.
        </div>
    </div>

    <div class="list-block block">
        <?php echo $this->mobileTransportsList($transports) ?>
    </div>
</div>