<tr><td style="padding: 0 20px">
    <table style="min-width: 240px; margin: 0 auto; font-size: 14px;"><tbody>

    <tr><td colspan="2" height="20" style="height: 20px;"></td></tr>

    <tr>
        <td colspan="2" width="100%" style="padding-bottom: 6px; text-align: center">
            <span class="header">Новый вопрос на сайте</span>
        </td>
    </tr>

    <tr><td colspan="2" height="20" style="height: 10px;"></td></tr>

    <tr>
        <td colspan="2" width="100%" style="text-align: left;">
            <?php echo $comment->get('question') ?>
        </td>
    </tr>

    <tr><td colspan="2" height="10" style="height: 10px;"></td></tr>


    <tr><td colspan="2" style="text-align: center;">
            <a href="http://<?php echo $_SERVER['HTTP_HOST'] ?>/admin/comments/comments/edit/?id=<?php echo $comment->getId() ?>" class="btn" style="width: 240px;">Подтвердить почту</a>
        </td></tr>

    <tr><td colspan="2" height="20" style="height: 20px;"></td></tr>

    </tbody></table>
</td></tr>