<?php
echo $this->tags([
    ['row', 'style' => ['padding-top' => '30px'], 'tags' => [
        ['td', 'align' => 'left', 'tags' => [
            ['h2', 'text' => 'Поступил ответ на ваш вопрос'],
            ['p', 'text' => $this->tr('Вопрос') . ': ' . $comment->get('question')],
            ['p', 'text' => $this->tr('Ответ') . ': ' . $comment->get('answer'), 'style' => ['padding-bottom' => '30px']],
            ['btn', 'href' => 'https://' . $_SERVER['HTTP_HOST'] . '' . $comment->getParent()->getPublicUrl() . '/', 'text' => 'Открыть на сайте'],
        ]],
    ]],
]);