<?php
echo $this->tags([
    ['row', 'style' => ['padding-top' => '30px'], 'tags' => [
        ['td', 'align' => 'left', 'tags' => [
            ['h2', 'text' => 'Новый вопрос на сайте'],
            ['p', 'text' => 'Имя: ' . $comment->get('name')],
            ['p', 'text' => 'Контакты: ' . $comment->get('contact')],
            ['p', 'text' => 'Вопрос: ' . $comment->get('question')],
            ['p', 'text' => 'Язык: ' . $comment->get('lang'), 'style' => ['padding-bottom' => '30px']],
            ['btn', 'href' => 'https://' . $_SERVER['HTTP_HOST'] . '/admin/comments/comments/edit/?id=' . $comment->getId() . '/', 'text' => 'Ответить'],
        ]],
    ]],
]);