</div>
<div id="footer">
    <a class="call" href="tel:+78129571765"><i class="fas fa-microphone"></i> <?php echo $this->tr('Сделать звонок') ?></a>
</div>

<?php
echo $this->settings->get('html_body');
?>

<?php
$jsonLd = [
    '@context'  => 'http://schema.org',
    '@type'     => 'Organization',
    'url'       => $settings->get('domain'),
    'name'      => $settings->get('site_name'),
    'logo'      => $settings->get('domain') . '/images/logo-b.png',
    'telephone' => $contacts->get('phone_1'),
    'email'     => $contacts->get('email'),
    'contactPoint' => (object) [
        '@type'       => 'ContactPoint',
        'telephone'   => $contacts->get('phone_1'),
        'contactType' => 'sales',
        'areaServed'  => ['RU']
    ],
    /*'sameAs' => [
        $contacts->get('vkontakte')
    ],*/
];
?>

<script type="application/ld+json">
<?php echo \Zend\Json\Json::encode((object) $jsonLd); ?>
</script>

<?php
$jsonLd = [
    '@context'  => 'http://schema.org',
    '@type'     => 'WebSite',
    'url'       => $settings->get('domain'),
    'name'      => $settings->get('site_name'),
    /*'potentialAction' => (object) [
        '@type'       => 'SearchAction',
        'target'      => $settings->get('domain') . '/catalog/search/?query={search_term}',
        'query-input' => 'required name=search_term',
    ],*/
];
?>
</body>
</html>