<?php
$this->generateMeta(true);

$this->headLink()
    ->prependStylesheet(\Aptero\Compressor\Compressor::getPublicLink('css', 'mobile'))
    ->prependStylesheet('/fonts/fonts.css')
    ->prependStylesheet('//fonts.googleapis.com/css?family=Merriweather:400,400i,700,700i')
    ->prependStylesheet('//use.fontawesome.com/releases/v5.4.1/css/all.css');

$this->headScript()
    ->prependFile(\Aptero\Compressor\Compressor::getPublicLink('js', 'mobile'))
    ->prependFile('//ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js')
    ->prependFile('//ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js')
    //->prependFile('/engine/js/jquery/jquery-ui.js')
    //->prependFile('/engine/js/jquery/jquery.js')
;

if(MODE != 'dev') {
    $this->headScript()
        ->prependFile('/js/counters/chat.js', null, ['async' => true])
        ->prependFile('/js/counters/yandex.js', null, ['async' => true])
        ->prependFile('/js/counters/google.js', null, ['async' => true]);
}

$language = \Translator\Model\Translator::getInstance();
$langCode = $language->getLangCode();
?>
<!DOCTYPE html>
<html lang="<?php echo $langCode ?>">
<head>
    <meta charset="utf-8">
    <meta name="theme-color" content="#d1302d">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="icon" type="image/png" href="/images/logos/16.png" sizes="16x16">

    <?php echo $this->headTitle() . "\n";
    echo $this->headMeta();
    echo $this->headLink();
    echo $this->headScript();
    echo $this->settings->get('html_head')
    ?>
    <script>
        $.languages.setLanguage('<?php echo $langCode ?>');
        $.config.euroRate = <?php echo $settings->get('euro_rate') ?>;
    </script>
</head>
<body>
<?php if(empty($_COOKIE['greeting']) && isset($_COOKIE['metric']) && $_COOKIE['metric'] == 'init') { ?>
    <script>
        $.fancybox.open({
            src: '/greeting/',
            type: 'ajax',
            opts: {
                ajax: {
                    settings: {}
                },
                afterLoad: function(e) {
                    initElements(e.$refs.slider);
                }
            }
        });
    </script>
    <?php
}
setcookie("greeting", 1, time()+(31104000), '/');
?>

<div id="fog"></div>

<div id="header">
    <a href="/" class="item logo">
        Gute <span>Reise</span>
    </a>

    <a href="/cart/" class="cart">
        <div class="trigger">
            <div class="icon">
                <div class="counter"></div>
            </div>
        </div>
    </a>

    <span class="language">
        <?php echo $this->languageSelect() ?>
    </span>

    <div class="nav">
        <div class="trigger">
            <div class="icon">
                <span></span>
                <span></span>
                <span></span>
            </div>
        </div>
        <div class="outer">
            <div class="box">
                <ul class="menu">
                    <li class="search" >
                        <input class="query" placeholder="Поиск">
                    </li>
                    <li><a href="/excursions/"><i class="fas fa-university"></i> <?php echo $this->tr('Экскурсии') ?></a></li>
                    <li><a href="/tours/"><i class="fas fa-university"></i> <?php echo $this->tr('Туры') ?></a></li>
                    <li><a href="/hotels/"><i class="far fa-building"></i> <?php echo $this->tr('Отели') ?></a></li>
                    <li><a href="/transport/"><i class="fas fa-bus"></i> <?php echo $this->tr('Транспорт') ?></a></li>
                    <li><a href="/about/"> <?php echo $this->tr('О компании') ?></a></li>
                    <li><a href="/contacts/"><?php echo $this->tr('Контакты') ?></a></li>
                </ul>

                <div class="contacts">
                    <div class="row">
                        <a href="<?php echo $this->link($contacts->get('email')) ?>"><i class="far fa-envelope"></i> <?php echo $contacts->get('email') ?></a>
                    </div>
                    <div class="row">
                        <a href="<?php echo $this->link($contacts->get('phone_1')) ?>"><i class="fa fa-phone"></i> <?php echo $contacts->get('phone_1') ?></a>
                    </div>
                    <div class="row">
                        <a href="<?php echo $this->link($contacts->get('phone_2')) ?>"><i class="fa fa-phone"></i> <?php echo $contacts->get('phone_2') ?></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div id="container">