<div class="std-popup order-popup">
    <div class="header">
        <?php echo $this->tr($hotel->get('name')); ?>
    </div>
    <div class="body std-form">
        <form action="/hotels/order/?id=<?php echo $hotel->getId(); ?>" class="form-box common-form">
            <?php echo $this->formElement($form->get('id')); ?>
            <div class="cols">
                <div class="col-25">
                    <div class="row">
                        <?php echo $this->formRow($form->get('date')); ?>
                    </div>
                </div>
                <div class="col-25 ">
                    <div class="row">
                    <?php echo $this->formRow($form->get('time')); ?>
                    </div>
                </div>
                <div class="col-25 ">
                    <div class="row">
                    <?php echo $this->formRow($form->get('adults')); ?>
                    </div>
                </div>
                <div class="col-25 ">
                    <div class="row">
                    <?php echo $this->formRow($form->get('children')); ?>
                    </div>
                </div>
            </div>
            <div class="cols">
                <div class="col-25">
                    <?php echo $this->formRow($form->get('lang_id')); ?>
                </div>
                <div class="col-25">
                    <?php echo $this->formRow($form->get('name')); ?>
                </div>
                <div class="col-25">
                    <?php echo $this->formRow($form->get('phone')); ?>
                </div>
                <div class="col-25">
                    <?php echo $this->formRow($form->get('email')); ?>
                </div>
            </div>
            <?php if($hotel->get('transport') == \Hotels\Model\Hotel::TRANSPORT_AUTO) { ?>
            <div class="cols">
                <div class="col-100">
                    <?php echo $this->formRow($form->get('place_start')); ?>
                </div>
            </div>
            <?php } ?>

            <div class="form-errors"></div>

            <div class="btns">
                <input type="submit" value="<?php echo $this->tr('Забронировать') ?>" class="btn yellow order">
                <div class="price-box"></div>
            </div>
        </form>
        <div class="success-box">
            <div class="sb-title"><?php echo $this->tr('Экскурсия забронирована') ?></div>
            <div class="sb-desc"><?php echo $this->tr('Наш менеджер перезвонит вам в ближайшее время для уточнения деталей заказа') ?></div>
            <div class="sb-btns">
                <span class="btn yellow" data-fancybox-close><?php echo $this->tr('Закрыть') ?></span>
            </div>
        </div>
    </div>
</div>

<script>
var popup = $('.order-popup');
var form = $('form', popup);

form.formSubmit({
    success: function(resp, form){
        $(form).fadeOut(200, function(){
            $('.success-box', popup).fadeIn(200);
        });
    }
});

var cForm = new CommonForm(form);

var timer = null;
$('input, select', form).on('keyup change', function () {
    clearTimeout(timer);
    timer = setTimeout(function() {
        $.ajax({
            url: '/hotels/get-price/',
            method: 'post',
            data: $.aptero.serializeArray(form),
            success: function (resp) {
                $('.price-box, .form-errors', form).empty();

                var data = resp.data;
                var html = '';

                var errorsHtml = '';

                $.each(data.errors, function(key, val) {
                    errorsHtml += '<div class="error">' + val + '</div>';
                });

                if(errorsHtml) {
                    $('.price-box', form).html(errorsHtml);
                    return;
                }

                html +=
                    '<div class="price">' + $.aptero.price(data.price, true) + '</div>';
                if(!data.child) {
                    html +=
                        '<div class="notice">' + $.aptero.price(data.adult, true) + ' <?php echo $this->tr('за человека') ?></div>';
                } else {
                    html +=
                        '<div class="notice">' +
                            'взрослый - ' + $.aptero.price(data.adult, true) + ', ' +
                            'детский - '  + $.aptero.price(data.child, true) +
                        '</div>';
                }
                $('.price-box', form).html(html);
            }
        });
    }, 200);
}).trigger('change');
</script>