<?php echo $this->header([
    'background' => '/images/headers/cars.jpg'
]); ?>

<div class="block module-items-block sidebar-aware">
    <div class="container">
        <div class="col-left sidebar">
            <div class="slider filters">
                <?php
                /*echo $this->ExcursionsWidgets('types', [
                    'value'   => $filters['type'],
                    'data'    => \Excursions\Model\ExcursionType::getEntityCollection()
                ]);

                $museums = \Museums\Model\Museum::getEntityCollection();
                $museums->select()->where(['parent' => 0]);

                echo $this->ExcursionsWidgets('museums', [
                    'value'   => $filters['museums'],
                    'data'    => $museums
                ]);*/
                ?>
            </div>
        </div>
        <div class="col-right">
            <div class="items-list items-3 transports-list">
                <?php echo $this->transportsList($transports) ?>
            </div>
        </div>
        <div class="clear"></div>
    </div>
</div>