<?php echo $this->header([
    'background' => '/images/headers/cars.jpg'
]); ?>

<div class="block module-items-block sidebar-aware">
    <div class="container">
        <div class="sidebar">
            <div class="slider filters">
                <div class="widget menu">
                    <div class="header">Категории</div>
                    <div class="body">
                        <a href="/transport/?type=<?= \Transports\Model\Transport::TYPE_AUTO ?>" class="btn">Автомобили</a>
                        <a href="/transport/?type=<?= \Transports\Model\Transport::TYPE_BOAT ?>" class="btn">Катера</a>
                        <a href="/transport/?type=<?= \Transports\Model\Transport::TYPE_COPTER ?>" class="btn">Вертолеты</a>
                    </div>
                </div>
            </div>
        </div>
        <div class="content">
            <div class="items-list items-3 transports-list">
                <?php echo $this->transportsList($transports) ?>
            </div>
        </div>
        <div class="clear"></div>
    </div>
</div>