<?php /*echo $this->header([
    'background' => '/images/headers/petergof.jpg'
]); ?>

<div class="block transport-block">
    <div class="col-l">
        <div class="gallery">
            <div class="pic">
                <img src="<?php echo $transport->getPlugin('image')->getImage('m') ?>" alt="<?php echo $transport->get('name') ?>">
            </div>
        </div>
    </div>
    <div class="col-r">
        <h2><?php echo $transport->get('name') ?></h2>
        <div class="std-text"><?php echo $transport->get('text') ?></div>
    </div>
    <div class="clear"></div>
</div>*/ ?>

<div class="std-popup order-popup">
    <div class="header">
        <?php echo $transport->get('name'); ?>
    </div>
    <div class="body">
        asdasd
    </div>
</div>

