<?php echo $this->header([
    'background' => $headerBg,
    'wrapper'    => true
]); ?>

<div class="block gray">
    <div class="wrapper">
        <div class="module-item-block transport-block">
            <div class="content">
                <?php echo $this->gallery($transport) ?>

                <div class="desc-box">
                    <h2><?php echo $this->tr($transport->get('name')) ?></h2>
                    <div class="std-text"><?= $this->tr($transport->get('text')) ?></div>
                </div>

                <div class="attrs-list">
                    <?php
                    foreach ($transport->getPlugin('props') as $row) {
                        echo
                        '<div class="row">'.
                            $row->get('name').
                        '</div>';
                    }
                    ?>
                </div>
            </div>
            <div class="sidebar">
                <div class="slider">
                    <?php
                    $html =
                        '<form action="/transport/get-price/" method="post" class="transport-form common-form">'.
                            '<input type="hidden" name="id" value="' . $transport->getId() . '">'.
                            $this->commonForm($commonForm, [
                                ['field' => 'date', 'icon' => 'far fa-calendar-alt'],
                                ['field' => 'time', 'icon' => 'far fa-clock'],
                                ['field' => 'duration', 'icon' => 'fas fa-stopwatch'],
                                ['field' => 'adults', 'icon' => 'fas fa-user'],
                            ]).
                            '<div class="price-box std-errors"></div>'.
                            '<div class="btns">'.
                                '<span class="btn yellow order">' . $this->tr('Забронировать') . '</span>'.
                            '</div>'.
                        '</form>';

                    echo $html;
                    ?>
                </div>
            </div>
        </div>
    </div>
</div>