<?php echo $this->header([
    'background' => '/images/headers/isaak.jpg'
]); ?>

<div class="block module-items-block sidebar-aware" id="items-list-anchor">
    <div class="container">
        <div class="content">
            <div class="items-list items-4 excursions-list">
                <?php echo $this->excursionsList($tours, $sidebarForm) ?>
            </div>
        </div>
        <div class="clear"></div>
    </div>
</div>
