<div class="excursions-block">
    <div class="info-block block">
        <div class="icon"></div>
        <div class="text">Вы можете выбрать как готовый маршрут, так и составить его самостоятельно.</div>
    </div>

    <div class="filters-block block">
        <div class="search">
            <input type="text" placeholder="Найти экскурсию">
        </div>
    </div>

    <div class="list-block block">
        <?php echo $this->mobileExcursionsList($excursions) ?>
    </div>
</div>