<?php /*echo $this->header([
    'background' => $headerImage,
    'wrapper'    => true
]);*/

$blocks = [];
$menu = [
    'desc' => [
        'href'  => '',
        'class' => 'item active',
        'name'  => '<i class="fal fa-file-alt"></i> ' . $this->tr('Описание'),
    ],
];

if($excursion->getPlugin('plan')->count()) {
    $menu['plan'] = [
        'href'  => '.anchor-plan',
        'class' => 'item anchor',
        'name'  => '<i class="fal fa-map"></i> ' . $this->tr('План'),
    ];
}

if($excursion->getPlugin('museums')->count()) {
    $menu['museums'] = [
        'href'  => '.anchor-attractions',
        'class' => 'item anchor',
        'name'  => '<i class="fal fa-university"></i> ' . $this->tr('Достопримечательности'),
    ];
}

$menu['comments'] = [
    'href'  => '.excursion-block .comments',
    'class' => 'item anchor',
    'name'  => '<i class="fal fa-comments"></i> ' . $this->tr('Вопросы'),
];

$isTour = $excursion->isTour();
$duration = $isTour ? count($excursion->get('db_data')->days) : $excursion->get('db_data')->days[0]->duration;

//module-item-block
?>

<div class="block module-item-block excursion-block sidebar-aware sidebar-right">
    <div class="wrapper">
    <div class="container">
    <div class="content">
    <div class="panel">
        <?php /*
        <div class="menu">
            <?php
            foreach ($menu as $item) {
                echo
                    '<a href="' . $item['href'] . '" class="' . $item['class'] . '">' . $item['name'] . '</a>';
            }
            ?>
        </div>

        <?php
        $season = $excursion->checkDate();
        if(!$season['status']) {
            echo
                '<div class="season">'.
                    '<div class="title">' . $season['header'] . '</div>'.
                    '<div class="desc">' . $season['desc'] . '</div>'.
                '</div>';
        }
        ?>
        */ ?>

        <?php echo '<h1' . (mb_strlen($this->header) > 40 ? ' style="font-size: 35px"' : '') . '>' . $this->header . '</h1>' ?>
        <?php echo $this->gallery($excursion) ?>

        <div class="desc-box">
            <div class="std-text"><?php echo $this->tr($excursion->get('text')) ?></div>

            <div class="attrs-list">
                <div class="row">
                    <i class="fal fa-clock"></i>
                    <?php if($excursion->get('place_and_time')) {
                        echo $this->tr('Место и время начала: ' . $excursion->get('place_and_time'));
                    } else {
                        echo $this->tr('Место и время начала экскурсии по вашему желанию');
                    }
                    ?>
                </div>
                <div class="row">
                    <i class="fal fa-map-marker-alt"></i>
                    <?php
                    if(!$isTour) {
                        echo
                            $this->tr('Длительность экскурсии - ').
                            $this->declension($duration, ['час', 'часа', 'часов']);
                    } else {
                        echo
                            $this->tr('Длительность тура - ').
                            $this->declension($duration, ['день', 'дня', 'дней']);
                    }
                    ?>
                </div>
                <div class="row">
                    <i class="fal fa-clipboard-list-check"></i>
                    <?php
                    echo $this->tr('В стоимость включено:');

                    $html =
                        '<div class="sub">';

                    foreach ($excursion->getPlugin('pricetable') as $row) {
                        $text = $row->get('text');

                        if($text == '%TRANSPORT%') {
                            $transports = \Transports\Model\Transport::getEntityCollection();
                            $transports->select()->where(['type' => \Transports\Model\Transport::TYPE_AUTO, 'id' => [1, 2, 3]]);

                            $text = $this->tr('Аренда') . ' ';
                            foreach ($transports as $transport) {
                                $text .=
                                    '<a class="popup" href="' . $transport->getUrl() . '">' . $this->tr($transport->get('name')) . '</a> / ';
                            }
                            $text = rtrim($text, ' /');
                        } elseif('%GUIDE%') {
                            $text = $this->tr('Услуги русскоговорящего гида');
                        } elseif('%MUSEUM%') {
                            $text = $this->tr('Входные билеты в музеи');
                        } else {
                            $text = $this->tr($text);
                        }

                        $html .=
                            '<div class="row">- ' . $text . '</div>';
                    }

                    $html .= '</div>';

                    echo $html;
                    ?>
                </div>
            </div>

            <div class="panel2 info">
                <div class="icon"></div>

                <div class="text">
                <?= $this->tr('Все экскурсии на сайте являются индивидуальными, то есть Вам предоставляется персональный гид и транспорт.
                Экскурсия начинается в удобное для Вас время, в любом месте города. Вход в музеи осуществляется без очереди.
                Мы можем организовать встречу в аэропорту и на вокзале, поможем с выбором гостиницы. Наша фирма работает с
                туристами из России, Европы и Китая. Количество туристов в группе не ограничено.'); ?>
                </div>

                <div class="contacts">
                    <div class="item">
                        <i class="fal fa-phone"></i>
                        <?= $contacts->get('phone_1') ?>
                    </div>
                    <div class="item">
                        <i class="fal fa-envelope"></i>
                        <?= $contacts->get('email') ?>
                    </div>
                </div>
            </div>
        </div>
        </div>

        <?php if(array_key_exists('plan', $menu)) { ?>
        <div class="panel">

            <h2><?php echo $this->tr('План экскурсии') ?></h2>

            <div class="plan">
                <?php
                $plan = $excursion->getPlugin('plan');

                $html = '';

                $days = $duration;

                $icons = [
                    'museum' => '<i class="fal fa-university"></i>',
                    'park'   => '<i class="fal fa-tree"></i>',
                    'marker' => '<i class="fal fa-map-marker-alt"></i>',
                    'cafe'   => '<i class="fal fa-coffee"></i>',
                    'anchor' => '<i class="fal fa-anchor"></i>',
                    'auto'   => '<i class="fal fa-bus"></i>',
                ];

                foreach ($plan as $day) {
                    $html .=
                        '<div class="day">'.
                            '<div class="stage">'.
                                '<div class="icon">' . $icons[$day->get('icon')] . '</div>'.
                            '</div>'.
                            '<div class="desc">'.
                                '<div class="header">'. $this->tr($day->get('header')) . '</div>'.
                                ($day->get('text') ? '<div class="text panel2">'. $this->tr($day->get('text')) . '</div>' : '').
                            '</div>'.
                        '</div>';
                }

                echo $html;
                ?>
            </div>
        </div>
        <?php } ?>

        <div class="panel">
        <?php echo $this->comments([
            'depend_id' => $excursion->getId(),
            'depend_type' => \Comments\Model\Comment::TYPE_EXCURSION,
        ]); ?>
        </div>

        <?php if(array_key_exists('museums', $menu)) { ?>
            <div class="panel">
                <h2><?php echo $this->tr('Похожие экскурсии') ?></h2>
                <?php echo $this->shortList($excursion->getPlugin('reco'), ['desc' => false]) ?>
            </div>
        <?php } ?>
    </div>
    <div class="sidebar">
        <div class="slider">
            <?php
            $html =
                '<form action="/excursions/get-price/" method="post" class="widget excursion-form common-form">'.
                    '<input type="hidden" name="lang_id" value="' . \Translator\Model\Translator::getInstance()->getLangId() . '">'.
                    $this->commonForm($commonForm, [
                        ['field' => 'date', 'icon' => 'fal fa-calendar-alt'],
                        ['field' => 'time', 'icon' => 'fal fa-clock'],
                        ['field' => 'adults', 'icon' => 'fal fa-user'],
                        ['field' => 'children', 'icon' => 'fal fa-child'],
                    ]).
                    '<div class="body">'.
                        '<div class="price-box std-errors"></div>'.
                        '<div class="btns">'.
                            '<span class="btn yellow order">' . $this->tr('Бронировать') . '</span>'.
                        '</div>'.
                    '</div>'.
                '</form>';

            echo $html;
            ?>
        </div>
    </div>
    </div>
    </div>
</div>

<script>
$(function () {
    var form = $('.excursion-form');
    var timer = null;

    form.formSubmit({
        success: function(resp, form){
            updatePrice(resp.data);
        }
    });

    $('input, select', form).on('keyup change', function () {
        clearTimeout(timer);
        timer = setTimeout(function() {
            form.submit();
        }, 200);
    }).trigger('change');

    function updatePrice(data) {
        var html = '';
        new CommonForm(form);
        var errorsHtml = '';

        $.each(data.errors, function(key, val) {
            errorsHtml += '<div class="error">' + val + '</div>';
        });

        if(errorsHtml) {
            $('.price-box', form).html(errorsHtml);
            return;
        }

        html +=
            '<div class="price"><span>' + $.aptero.price(data.price) + '</span></div>';
        if(!data.child) {
            html +=
                '<div class="notice"><b>' + $.aptero.price(data.adult) + '</b> <?php echo $this->tr('за человека') ?></div>';
        } else {
            html +=
                '<div class="notice">' +
                    '<?php echo $this->tr('взрослый') ?> - <b>' + $.aptero.price(data.adult) + '</b>, ' +
                    '<?php echo $this->tr('детский') ?> - <b>'  + $.aptero.price(data.child) + '</b>' +
                '</div>';
        }

        $('.price-box', form).html(html);
    }

    var cForm = new CommonForm(form);

    $('.order', form).on('click', function() {
        var data = $.aptero.serializeArray(form);
        data.id = <?php echo $excursion->getId() ?>;

        $.fancybox.open({
            src: '/excursions/order/',
            type: 'ajax',
            opts: {
                ajax: {
                    settings: {
                        method: 'get',
                        data: data
                    }
                },
                afterLoad: function(e, slide) {
                    initElements(slide.$slide);
                }
            }
        });
    });
});
</script>