<?php echo $this->header([
    'background' => $headerImage,
    'wrapper'    => true
]); ?>

<div class="block gray">
    <div class="wrapper">
    <div class="excursion-block">
    <div class="content">
        <div class="menu">
            <a href="" class="item active">
                <i class="far fa-file-alt"></i>
                Описание
            </a>
            <a href=".excursion-block .gallery" class="item anchor">
                <i class="fas fa-camera"></i>
                Фотографии
            </a>
            <a href=".excursion-block .comments" class="item anchor">
                <i class="far fa-comment"></i>
                Комментарии
            </a>
        </div>

        <?php
        $html =
            '<div class="gallery">'.
                '<ul class="list">';

        $html .=
            '<li data-thumb="' . $excursion->getPlugin('image')->getImage('hr') . '">'.
                '<img src="' . $excursion->getPlugin('image')->getImage('g') . '" alt="">'.
            '</li>';

        foreach ($excursion->getPlugin('images') as $image) {
            $html .=
                '<li data-thumb="' . $image->getImage('hr') . '">'.
                    '<img src="' . $image->getImage('g') . '" alt=""></li>'.
                '</li>';
        }

        $html .=
                '</ul>'.
            '</div>';
        echo $html;
        ?>

        <div class="desc-box">
            <h2><?php echo $excursion->get('name') ?></h2>
            <div class="std-text"><?php echo $excursion->get('text') ?></div>

            <div class="attrs-list">
                <div class="row">
                    <div class="label">Длительность</div>
                    Экскурсия рассчитана на 5 часов
                </div>
                <?php /*
                <div class="row">
                    <div class="label">Время и место начала</div>
                    Начало и окончание экскурсии в любом месте города по Вашему желанию
                </div>
                */ ?>
                <div class="row">
                    <div class="label">В стоимость включено</div>
                    <div class="row"><i class="fas fa-check"></i>  Аренда <a class="popup" href="/transport/mercedes-benz-e-class/">Мерседеса Е 211</a>/<a href="">Мерседеса Виано</a>/<a href="">Мерседеса Спринтера</a></div>
                    <div class="row"><i class="fas fa-check"></i>  Входные билеты в Екатерининский дворец и Екатерининский парк</div>
                    <div class="row"><i class="fas fa-check"></i>  Услуги персонального гида</div>
                </div>
            </div>
        </div>
        <div class="std-header">
            <h2>План экскурсии</h2>
            <div class="separ"></div>
        </div>

        <div class="plan">
            <?php
            $plan = $excursion->getPlugin('plan');

            $html = '';

            $icons = [
                'museum' => '<i class="fas fa-university"></i>',
                'park'   => '<i class="fas fa-tree"></i>',
                'marker' => '<i class="fas fa-map-marker-alt"></i>',
            ];

            foreach ($plan as $day) {
                $html .=
                    '<div class="day">'.
                        '<div class="stage">'.
                            '<div class="icon">' . $icons[$day->get('icon')] . '</div>'.
                        '</div>'.
                        '<div class="desc">'.
                            '<div class="header">'. $day->get('header') . '</div>'.
                            '<div class="text">'. $day->get('text') . '</div>'.
                        '</div>'.
                    '</div>';
            }

            echo $html;
            ?>
        </div>

        <?php /*
        <div id="anc-ex-gallery" class="gallery">
            <h2>Из нашей галлереи</h2>

            <?php
            $html =
                '<div class="list">';

            $html .=
                '<a href="' . $excursion->getPlugin('image')->getImage('hr') . '">'.
                    '<img src="' . $excursion->getPlugin('image')->getImage('s') . '" alt="">'.
                '</a>';

            foreach ($excursion->getPlugin('images') as $image) {
                $html .=
                    '<a href="' . $image->getImage('hr') . '">'.
                        '<img src="' . $image->getImage('s') . '" alt=""></a>'.
                    '</a>';
            }

            $html .=
                '</div>';
            echo $html;
            ?>
        </div>
        */ ?>

        <?php echo $this->comments([
            'depend_id' => $excursion->getId(),
            'depend_type' => \Comments\Model\Comment::TYPE_EXCURSION,
        ]); ?>
    </div>
    <div class="sidebar">
        <div class="slider">
            <?php
            $html =
                '<form action="/excursions/get-price/" method="post" class="excursion-form common-form">'.
                    //'<div class="header">Стоимость экскурсии</div>'.
                    $this->commonForm($commonForm).
                    '<div class="price-box std-errors"></div>'.
                    '<div class="btns">'.
                        '<span class="btn yellow order">Забронировать</span>'.
                    '</div>'.
                '</form>';

            echo $html;
            ?>
        </div>
    </div>
    <div class="clear"></div>
    </div>
    </div>
</div>

<script>
$(function () {
    var gallery = $('.gallery .list', '.excursion-block');

    gallery.lightSlider({
        gallery: true,
        item: 1,
        vertical: true,
        verticalHeight: 500,
        vThumbWidth: 100,
        thumbItem: 7,
        thumbMargin: 4,
        slideMargin: 0
    });

    var form = $('.excursion-form');
    var timer = null;

    form.formSubmit({
        success: function(resp, form){
            updatePrice(resp.data);
        }
    });

    $('input, select', form).on('keyup change', function () {
        clearTimeout(timer);
        timer = setTimeout(function() {
            form.submit();
        }, 200);
    }).trigger('change');

    function updatePrice(data) {
        var html = '';

        var errorsHtml = '';

        $.each(data.errors, function(key, val) {
            errorsHtml += '<div class="error">' + val + '</div>';
        });

        if(errorsHtml) {
            $('.price-box', form).html(errorsHtml);
            return;
        }

        html +=
            '<div class="price"><span>' + $.aptero.price(data.price) + '</span> <i class="fas fa-ruble-sign"></i></div>';
        if(!data.child) {
            html +=
                '<div class="notice"><b>' + $.aptero.price(data.adult) + '</b> <i class="fas fa-ruble-sign"></i> за человека</div>';
        } else {
            html +=
                '<div class="notice">' +
                    'взрослый - <b>' + $.aptero.price(data.adult) + '</b> <i class="fas fa-ruble-sign"></i>, ' +
                    'детский - <b>'  + $.aptero.price(data.child) + '</b> <i class="fas fa-ruble-sign"></i>' +
                '</div>';
        }

        $('.price-box', form).html(html);
    }

    var cForm = new CommonForm(form);

    $('.order', form).on('click', function() {
        var data = $.aptero.serializeArray(form);
        data.id = <?php echo $excursion->getId() ?>;

        $.fancybox.open({
            src: '/excursions/order/',
            type: 'ajax',
            opts: {
                ajax: {
                    settings: {
                        method: 'get',
                        data: data
                    }
                },
                afterLoad: function(e, slide) {
                    initElements(e.$refs.slider);
                }
            }
        });
    });
});
</script>