<?php echo $this->header([
    'background' => '/images/headers/petergof.jpg'
]); ?>

<div class="block module-items-block sidebar-aware">
    <div class="container">
        <div class="col-left sidebar">
            <div class="slider filters">
                <?php
                echo $this->ExcursionsWidgets('search', [
                    'value'   => $filters['search'],
                ]);

                $tags = \Excursions\Model\Tags::getEntityCollection();
                $tags->select()->where
                    ->greaterThan('count', 0);

                echo $this->ExcursionsWidgets('catalog', [
                    'value'   => $filters['tags'],
                    'data'    => $tags
                ]);
                /*echo $this->ExcursionsWidgets('types', [
                    'value'   => $filters['type'],
                    'data'    => \Excursions\Model\ExcursionType::getEntityCollection()
                ]);

                $museums = \Museums\Model\Museum::getEntityCollection();
                $museums->select()->where(['parent' => 0]);

                echo $this->ExcursionsWidgets('museums', [
                    'value'   => $filters['museums'],
                    'data'    => $museums
                ]);*/
                ?>
            </div>
        </div>
        <div class="col-right">
            <div class="items-list items-3 excursions-list">
                <?php echo $this->excursionsList($excursions, $sidebarForm) ?>
            </div>
        </div>
        <div class="clear"></div>
    </div>
</div>
