<?php echo $this->header([
    'background' => '/images/headers/' . $headerImage . '.jpg',
]); ?>

<div class="block module-items-block sidebar-aware excursion-items" id="items-list-anchor">
    <div class="container">
        <div class="sidebar">
            <div class="slider filters">
                <div class="widget catalog">
                    <div class="header"><?= $this->tr('Экскурсии') ?></div>
                    <div class="body">
                        <?php
                        $tags = \Excursions\Model\Tags::getEntityCollection();
                        $tags->select()->where
                            ->greaterThan('count', 0);

                        echo $this->ExcursionsWidgets([
                            'url'   => '/excursions/',
                        ], [
                            'search' => [
                                'value'   => $filters['search'],
                            ],
                            'catalog' => [
                                'value'   => $filters['tags'],
                                'data'    => $tags,
                            ],
                        ]);
                        ?>
                    </div>
                </div>
            </div>
        </div>
        <div class="content">
            <div class="items-list items-3 excursions-list">
                <?php echo $this->excursionsList($excursions, $sidebarForm) ?>
            </div>
        </div>
    </div>
</div>
