<?php echo $this->header([
    'background' => '/images/headers/petergof.jpg'
]); ?>

<div class="block module-items-block sidebar-aware" id="items-list-anchor">
    <div class="container">
        <div class="sidebar">
            <div class="slider filters">
                <?php
                $tags = \Excursions\Model\Tags::getEntityCollection();
                $tags->select()->where
                    ->greaterThan('count', 0);

                echo $this->ExcursionsWidgets([
                    'url'   => '/excursions/',
                ], [
                    'search' => [
                        'value'   => $filters['search'],
                    ],
                    'catalog' => [
                        'value'   => $filters['tags'],
                        'data'    => $tags
                    ],
                ]);
                ?>
            </div>
        </div>
        <div class="content">
            <div class="items-list items-3 excursions-list">
                <?php echo $this->excursionsList($excursions, $sidebarForm) ?>
            </div>
        </div>
        <div class="clear"></div>
    </div>
</div>
