<div class="block" id="footer">
    <div class="wide-wrapper">
        <div class="about">
            <div class="logo"></div>
            <div class="desc">
                <?php echo $this->tr('Мы работаем с 2007 года на рынке туристических услуг в сфере внутреннего и международного '.
                     'выездного туризма. Партнеры с которыми мы сотрудничаем -  это надежные и ответственные организации. '.
                     'Для нас нет мелочей в работе, все, что мы делаем должно соответствовать европейскому уровню качества.'); ?>
            </div>
        </div>
        <div class="menu">
            <ul class="item">
                <li class="title"><?php echo $this->tr('Услуги') ?></li>
                <li><a href="/excursions/"><?php echo $this->tr('Экскурсии') ?></a></li>
                <li><a href="/tours/"><?php echo $this->tr('Туры') ?></a></li>
                <li><a href="/hotels/"><?php echo $this->tr('Отели') ?></a></li>
                <li><a href="/transport/"><?php echo $this->tr('Аренда автотранспорта') ?></a></li>
                <li><a href="/transport/"><?php echo $this->tr('Аренда катеров и вертолетов') ?></a></li>
            </ul>
            <ul class="item">
                <li class="title"><?php echo $this->tr('О компании') ?></li>
                <li><a href="//"><?php echo $this->tr('Наша деятельность') ?></a></li>
                <li><a href="/guarant/"><?php echo $this->tr('Финансовые гарантии') ?></a></li>
                <li><a href="/documents/"><?php echo $this->tr('Документы') ?></a></li>
                <li><a href="/partners/"><?php echo $this->tr('Партнеры') ?></a></li>
            </ul>
            <div class="clear"></div>
        </div>
        <div class="contacts">
            <div class="row address">
                <i class="fas fa-map-marker-alt"></i>
                <?php echo $this->tr($contacts->get('address')) ?>
            </div>
            <div class="row">
                <i class="fas fa-phone"></i>
                <?php echo $contacts->get('phone_1') . ', ' . $contacts->get('phone_2') ?>
            </div>
            <div class="row">
                <i class="far fa-envelope-open"></i>
                <?php echo $contacts->get('email') ?>
            </div>
        </div>
    </div>
</div>

<?php
$jsonLd = [
    '@context'  => 'http://schema.org',
    '@type'     => 'Organization',
    'url'       => $settings->get('domain'),
    'name'      => $settings->get('site_name'),
    'logo'      => $settings->get('domain') . '/images/logo.png',
    'telephone' => $contacts->get('phone_1'),
    'email'     => $contacts->get('email'),
    'contactPoint' => (object) [
        '@type'       => 'ContactPoint',
        'telephone'   => $contacts->get('phone_1'),
        'contactType' => 'sales',
        'areaServed'  => ['RU']
    ],
    'sameAs' => [
        $contacts->get('vkontakte')
    ],
];
?>

<script type="application/ld+json">
<?php echo \Zend\Json\Json::encode((object) $jsonLd); ?>
</script>

<?php
$jsonLd = [
    '@context'  => 'http://schema.org',
    '@type'     => 'WebSite',
    'url'       => $settings->get('domain'),
    'name'      => $settings->get('site_name'),
    /*'potentialAction' => (object) [
        '@type'       => 'SearchAction',
        'target'      => $settings->get('domain') . '/search/?query={search_term}',
        'query-input' => 'required name=search_term',
    ],*/
];
?>

<script type="application/ld+json">
<?php echo \Zend\Json\Json::encode((object) $jsonLd); ?>
</script>
</body>
</html>