<?php
$this->generateMeta();

$version = $settings->get('html_css_js_version');

$this->headLink()
    ->prependStylesheet(\Aptero\Compressor\Compressor::getPublicLink('css'))
    ->prependStylesheet('//fonts.googleapis.com/css?family=Merriweather:400,400i,700,700i')
    //->prependStylesheet('//use.fontawesome.com/releases/v5.4.1/css/all.css')
;

$this->headScript()
    ->setAllowArbitraryAttributes(true)
    ->prependFile(\Aptero\Compressor\Compressor::getPublicLink('js'))
    //->prependFile('/js/libs/jquery-ui.js')
    //->prependFile('/js/libs/jquery.js')
    ->prependFile('//ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js')
    ->prependFile('//ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js')
    ;

if(MODE != 'dev') {
    /*$this->headScript()
        ->prependFile('/js/counters/chat.js', null, ['async' => true])
        ->prependFile('/js/counters/yandex.js', null, ['async' => true])
        ->prependFile('/js/counters/google.js', null, ['async' => true]);*/
}

$language = \Translator\Model\Translator::getInstance();
$langCode = $language->getLangCode();
?>
<!DOCTYPE html>
<html lang="<?php echo $langCode ?>">
<head>
    <meta charset="utf-8">
    <?php echo $this->headTitle() . "\n";
    echo $this->headMeta()  . "\n";
    echo $this->headLink()  . "\n";
    echo $this->headScript()  . "\n";
    echo $this->settings->get('html_head');
    ?>
    <script>
        $.languages.setLanguage('<?php echo $langCode ?>');
        $.currency.setCurrency('<?php echo \Application\Model\Currency::getInstance()->getCurrency() ?>');
    </script>
</head>
<body>
<div class="block" id="header">
    <div class="wrapper">
        <a href="/" class="logo"></a>
        <ul class="nav">
            <li><a href="/excursions/"><?php echo $this->tr('Экскурсии') ?></a></li>
            <li><a href="/tours/"><?php echo $this->tr('Туры') ?></a></li>
            <?php /*<li><a href="/hotels/"><?php echo $this->tr('Отели') ?></a></li> */?>
            <li><a href="/transport/"><?php echo $this->tr('Транспорт') ?></a></li>
            <li><a href="/about/"><?php echo $this->tr('О компании') ?></a></li>
            <li><a href="/attractions/"><?php echo $this->tr('Достопримечательности') ?></a></li>
        </ul>

        <?php echo $this->regionSettings() ?>

        <div class="contacts">
            <div class="phone"><?php echo $contacts->get('phone_1') ?></div>
            <div class="email"><?php echo $contacts->get('email') ?></div>
        </div>
    </div>
</div>