<?php echo $this->header([
    'background' => $headerBg
]); ?>

<div class="block module-items-block sidebar-aware">
    <div class="container">
        <div class="col-left sidebar">
            <div class="slider filters">
                <?php
                echo $this->ExcursionsWidgets('search', [
                    'value'   => $filters['search'],
                ]);

                $tags = \Museums\Model\Tags::getEntityCollection();
                $tags->select()->where
                    ->greaterThan('count', 0);

                echo $this->ExcursionsWidgets('catalog', [
                    'value'   => $filters['tags'],
                    'data'    => $tags
                ]);
                ?>
            </div>
        </div>
        <div class="col-right">
            <div class="items-list items-3 museums-list">
                <?php echo $this->museumsList($museums) ?>
            </div>
        </div>
        <div class="clear"></div>
    </div>
</div>
