<?php echo $this->header([
    'background' => $headerBg
]); ?>

<div class="block module-items-block sidebar-aware">
    <div class="container">
        <div class="sidebar">
            <div class="slider filters">
                <div class="widget catalog">
                    <div class="header"><?= $this->tr('Достопримечательности') ?></div>
                    <div class="body">
                        <?php
                        $tags = \Museums\Model\Tags::getEntityCollection();
                        $tags->select()->where
                            ->equalTo('parent', 0)
                            ->greaterThan('count', 0);

                        echo $this->ExcursionsWidgets([
                            'url'   => '/attractions/',
                        ], [
                            'search' => [
                                'value'   => $filters['search'],
                            ],
                            'catalog' => [
                                'value'   => $filters['tags'],
                                'data'    => $tags,
                                'counter' => false,
                                'all'     => ['text' => 'Показать все', 'url' => '/attractions/']
                            ],
                        ]);
                        ?>
                    </div>
                </div>
            </div>
        </div>
        <div class="content">
            <div class="items-list items-3 museums-list">
                <?php echo $this->museumsList($museums) ?>
            </div>
        </div>
        <div class="clear"></div>
    </div>
</div>
