<?php echo $this->header([
    'background' => $headerImage,
    'wrapper'    => true
]); ?>

<div class="block gray">
    <div class="wrapper">
        <div class="module-item-block museum-block">
            <div class="content pt">
                <?php echo $this->contentRender($museum->getPlugin('content')) ?>
                <?php echo $this->shortList($museum->getChildren(false), ['header' => 'Достопримечательности']); ?>

                <div class="notice">
                    Фирма “Gute Reise” рада предложить Вам экскурсии по Петербургу и пригородам. Мы можем организовать
                    экскурсию для группы или индивидуально с учетом ваших предпочтений. А также предоставить транспорт
                    и проживание в гостинице. По всем интересующим вопросам можно обратиться по телефону
                </div>
            </div>
            <div class="sidebar">
                <div class="slider">
                    <?php
                    $excursions = $museum->getPlugin('excursions');
                    $excursions->select()->limit(4);
                    echo $this->excursionsRecoWidget($excursions, ['header' => 'Экскурсии']) ?>
                </div>
            </div>
        </div>
    </div>
</div>