<?php echo $this->header([
    'background' => $headerImage,
    'wrapper'    => true
]); ?>

<div class="block gray">
    <div class="wrapper">
        <div class="module-item-block museum-block">
            <div class="content pt">
                <?php echo $this->contentRender($museum->getPlugin('content')) ?>
                <?php echo $this->shortList($museum->getChildren(false), ['header' => 'Достопримечательности']); ?>
            </div>
            <div class="sidebar">
                <div class="slider">
                    <?php echo $this->excursionsRecoWidget($museum->getPlugin('excursions')) ?>
                </div>
            </div>
        </div>
    </div>
</div>