<h1>
    <i class="fa module-icon-<?php echo $this->engine->module->get('module') ?>"></i>
    <?php echo $this->header ?>
</h1>

<?php $form = $this->editForm ?>
<?php echo $this->form()->openTag($form) ?>
<div class="edit-form std-form">
    <div class="tabs tabs-class" data-name="edit-tabs">
        <div class="tabs-header">
            <div class="tab" data-tab="general">Основное</div>
            <div class="tab" data-tab="mail">Почта</div>
            <div class="tab" data-tab="seo">Seo</div>
            <div class="tab" data-tab="notices">Уведомления</div>
        </div>
        <div class="tabs-body">
            <div class="tab" data-tab="general">
                <?php
                echo $this->adminFormRow($form->get('site_name'));
                echo $this->adminFormRow($form->get('video_summer'));
                echo $this->adminFormRow($form->get('video_winter'));
                echo $this->adminFormRow($form->get('site_color_bg'));
                echo $this->adminFormRow($form->get('site_color_title'));
                echo $this->adminFormRow($form->get('site_logo'));
                echo $this->adminFormRow($form->get('domain'));
                echo $this->adminFormRow($form->get('euro_rate'));
                ?>
            </div>
            <div class="tab" data-tab="seo">
                <?php
                echo $this->adminFormRow($form->get('html_css_js_version'));
                echo $this->adminFormRow($form->get('html_head'));
                echo $this->adminFormRow($form->get('html_body'));
                echo $this->adminFormRow($form->get('robots'));
                ?>
            </div>
            <div class="tab" data-tab="mail">
                <?php
                echo $this->adminFormRow($form->get('mail_sender'));
                echo $this->adminFormRow($form->get('mail_email'));
                echo $this->adminFormRow($form->get('mail_password'));
                echo $this->adminFormRow($form->get('mail_smtp'));
                ?>
            </div>
            <div class="tab" data-tab="notices">
                <?php
                echo $this->adminFormRow($form->get('admin_phone'));
                echo $this->adminFormRow($form->get('admin_email'));
                ?>
            </div>
        </div>
    </div>

    <div class="btn-box">
        <a class="btn btn-blue btn-submit" href="">
            <i class="fa fa-check"></i>
            Сохранить
        </a>
    </div>
</div>
<?php echo $this->form()->closeTag() ?>