<h1>
    <i class="fa module-icon-<?php echo $this->engine->module->get('module') ?>"></i>
    <?php echo $this->header ?>
</h1>

<?php $form = $this->editForm ?>
<?php echo $this->form()->openTag($form) ?>
<div class="edit-form std-form">
    <div class="tabs tabs-class" data-name="edit-tabs">
        <div class="tabs-header">
            <div class="tab" data-tab="general">Основное</div>
            <div class="tab" data-tab="points">Связи</div>
            <div class="tab" data-tab="photo">Фото</div>
            <div class="tab" data-tab="seo">SEO</div>
            <div class="tab" data-tab="text">Текст</div>
            <div class="tab" data-tab="map">Карта</div>
        </div>
        <div class="tabs-body">
            <div class="tab" data-tab="general">
                <?php
                echo $this->adminFormRow($form->get('image-image'));
                echo $this->adminFormRow($form->get('name'));
                echo $this->adminFormRow($form->get('header2'));
                echo $this->adminFormRow($form->get('preview'));
                echo $this->adminFormRow($form->get('url'));
                ?>
            </div>
            <div class="tab" data-tab="points">
                <?php echo $this->formRow($form->get('points-collection')); ?>
            </div>
            <div class="tab" data-tab="photo">
                <?php echo $this->formRow($form->get('images-images')); ?>
            </div>
            <div class="tab" data-tab="seo">
                <?php
                echo $this->adminFormRow($form->get('title'));
                echo $this->adminFormRow($form->get('description'));
                ?>
            </div>
            <div class="tab" data-tab="text">
                <?php
                echo $this->adminFormRow($form->get('text'));
                ?>
            </div>
            <div class="tab" data-tab="map">
                <?php
                echo $this->formElement($form->get('lat'));
                echo $this->formElement($form->get('lng'));
                ?>
                <div id="museum-map" style="height: 400px;"></div>
                <script>
                    var form = $('.edit-form');
                    var coords = {
                        lat: parseFloat($('[name="lat"]', form).val()),
                        lng: parseFloat($('[name="lng"]', form).val())
                    };

                    if(coords.lat == '' && coords.lng == '') {
                        coords = {lat: 59.927725, lng: 30.325141};
                    }

                    var map = new google.maps.Map(document.getElementById('museum-map'), {
                        center: coords,
                        zoom: 10,
                        styles: getGoogleMapStyle()
                    });

                    var marker = new google.maps.Marker({position: coords, map: map, draggable:true});

                    google.maps.event.addListener(marker, 'dragend', function() {
                        var pos = marker.getPosition();
                        $('[name="lat"]', form).val(pos.lat());
                        $('[name="lng"]', form).val(pos.lng());
                    });
                </script>
            </div>
        </div>
    </div>

    <div class="btn-box">
        <span class="btn btn-gray" onclick="history.back()">
            <i class="fa fa-reply"></i>
            Вернутся
        </span>
        <?php if($this->model->getId()) { ?>
            <a class="btn btn-red btn-remove-ck" href="#popup-delete">
                <i class="fa fa-times"></i>
                Удалить
            </a>
        <?php } ?>
        <a class="btn btn-blue btn-submit" href="">
            <i class="fa fa-check"></i>
            Сохранить
        </a>
    </div>
</div>
<?php echo $this->form()->closeTag() ?>

<div id="popup-delete" style="display: none;">
    <div style="text-align: center; margin-bottom: 10px;">Удалить запись?</div>
    <a href="" class="btn btn-green btn-remove" data-id="<?php echo $this->model->getId() ?>"><i class="fa fa-check"></i> Удалить</a>
    <a href="" class="btn btn-red" onclick="$.fancybox.close();"><i class="fa fa-times"></i> Отмена</a>
</div>