<div class="block main-block-1">
    <div class="video">
        <img src="images/placeholder.jpg" alt="" class="placeholder-image">
    </div>
    <div class="wrapper">
        <h1><?php echo $this->tr('Индивидуальные экскурсии и туры по Санкт-Петербургу') ?></h1>
        <div class="menu">
            <a href="/excursions/" class="btn yellow"><?php echo $this->tr('Экскурсии') ?></a>
            <a href="/tours/" class="btn yellow"><?php echo $this->tr('Туры') ?></a>
            <a href="/hotels/" class="btn yellow"><?php echo $this->tr('Отели') ?></a>
            <a href="/transport/" class="btn yellow"><?php echo $this->tr('Траспорт') ?></a>
        </div>

        <div class="tags">
            <?php /*
            $types = \Excursions\Model\ExcursionType::getEntityCollection();
            $types->select()
                ->where(['type' => \Excursions\Model\ExcursionType::TYPE_TAG]);

            foreach ($types as $type) {
                echo '<a href="' . $type->getUrl() . '" class="btn">' . $this->tr($type->get('name')) . '</a>';
            }
            */ ?>
            <?php
            $types = \Museums\Model\Museum::getEntityCollection();
            $types->select()->limit(14);

            foreach ($types as $type) {
                echo '<a href="' . $type->getUrl() . '" class="btn">' . $this->tr($type->get('name')) . '</a>';
            }
            ?>
        </div>
    </div>
</div>
<script>
    <?php
    $settings = \Application\Model\Settings::getInstance();

    $month = date('n');
    if($month < 2 || $month > 9) {
        $video = $settings->get('video_winter');
        $start = 7;
    } else {
        $video = $settings->get('video_summer');
        $start = 5;
    }
    ?>

    var block = $('.main-block-1');
    var video = $('.video', block);

    var marginTop = ((block.innerWidth() * 0.5625) - block.innerHeight()) / 2;

    video.YTPlayer({
        fitToBackground: true,
        controls: 0,
        videoId: '<?php echo $video ?>',
        pauseOnScroll: false,
        playerVars: {
            start: <?php echo $start ?>,
            autoplay: 1,
            controls: 0,
            showinfo: 0
        },
        callback: function() {
            video.children('.background').css({marginTop: -marginTop});
        }
    });
</script>

<div class="main-block main-block-2">
    <div class="block">
        <div class="header">
            <h2><?php echo $this->tr('Индивидуальные экскурсии по Петербургу') ?></h2>
            <div class="separ"></div>
            <div class="notice"><?php echo $this->tr('Эта серия настольных игр лучше всего передаёт атмосферу хтонического кошмара и безысходности из рассказов Лавкрафта.') ?></div>
        </div>
        <div class="menu">
            <a href="/excursions/overview/" class="item">
                <img src="/images/m-1.jpg" alt="<?php echo $this->tr('Обзорные экскурсии') ?>">
                <span class="desc"><?php echo $this->tr('Обзорные экскурсии') ?></span>
            </a>
            <a href="/excursions/museums/" class="item">
                <img src="/images/m-2.jpg" alt="Музеи и искуство">
                <span class="desc"><?php echo $this->tr('Музеи и искуство') ?></span>
            </a>
            <a href="/excursions/region/" class="item">
                <img src="/images/m-3.jpg" alt="<?php echo $this->tr('Загородные экскурси') ?>">
                <span class="desc"><?php echo $this->tr('Загородные экскурсии') ?></span>
            </a>
            <a href="/excursions/water/" class="item">
                <img src="/images/m-4.jpg" alt="<?php echo $this->tr('Экскурсии по рекам и каналам') ?>">
                <span class="desc"><?php echo $this->tr('Экскурсии по рекам и каналам') ?></span>
            </a>
            <a href="/excursions/unusual/" class="item">
                <img src="/images/m-5.jpg" alt="<?php echo $this->tr('Необычные экскурсии') ?>">
                <span class="desc"><?php echo $this->tr('Необычные экскурсии') ?></span>
            </a>
            <a href="/excursions/literature/" class="item">
                <img src="/images/m-6.jpg" alt="<?php echo $this->tr('Литературные экскурсии') ?>">
                <span class="desc"><?php echo $this->tr('Литературные экскурсии') ?></span>
            </a>
            <div class="clear"></div>
        </div>
    </div>
</div>

<div class="main-block-3">
    <div id="main-block-3-map" style="height: 450px;"></div>
    <div class="notice">
        <div class="title"><?php echo $this->tr('Составьте свой тур самостоятельно') ?></div>
        <div class="desc"><?php echo $this->tr('Мы поможем составить маршрут спецално для вас, поможем выбрать отель, встретить на
            вокзале и в аэропорту.') ?></div>
    </div>
    <script src="//maps.googleapis.com/maps/api/js?key=AIzaSyAk5H6D3lQ-4JvduK8UeT0rcqelhmN3QxY"></script>
    <script>
        var map = new google.maps.Map(document.getElementById('main-block-3-map'), {
            center: {lat: 59.936765, lng: 30.288474},
            zoom: 14,
            disableDefaultUI: true,
            scrollwheel: false,
            styles: getGoogleMapStyle()
        });

        var infoWindows = [];

        $.ajax({
            url: '/museums/get-map-attractions/',
            method: 'post',
            success: function (attractions) {
                $.each(attractions, function (key, val) {
                    var infoWindow = new google.maps.InfoWindow({
                        content: val.html
                    });

                    infoWindows.push(infoWindow);

                    var marker = new google.maps.Marker({
                        position: {lat: parseFloat(val.lat), lng: parseFloat(val.lng)},
                        icon: "/images/marker.png",
                        map: map
                    });

                    marker.addListener("click", function() {
                        $.each(infoWindows, function (key, val) { val.close() });
                        infoWindow.open(map, marker);
                    });
                });
            }
        });
    </script>
</div>

<div class="main-block-4">
    <div class="col-l">
        <div class="header"><?php echo $this->tr('Отзывы о нас') ?></div>
        <div class="reviews">
            <?php
            $html = '';

            $reviews = \Reviews\Model\Review::getEntityCollection();
            foreach ($reviews as $review) {
                $html .=
                    '<div class="review">'.
                    '<div class="name">' . $this->tr($review->get('name')) . '</div>'.
                    '<div class="stars">' .$this->tr($this->stars($review->get('stars')), false) . '</div>'.
                    '<div class="text">' . $this->tr($review->get('review')) . '</div>'.
                    '</div>';
            }

            echo $html;
            ?>
        </div>
    </div>
    <div class="col-r"></div>
    <div class="clear"></div>
</div>

<script>
    var block = $('.main-block-4');
    $('.reviews', block).lightSlider({
        item: 1,
        pager: false,
        loop: false,
        slideMove: 1,
        easing: 'cubic-bezier(0.25, 0, 0.25, 1)',
        speed: 600,
    });
</script>